### ISSUE TITLE
json config "replenishingItems" Does not work

### ISSUE THREAD

**Issue by DaveHyral** [alkyaly/Somnia-Fabric#1]
Extensively tested. No items whatsoever will recover Fatigue Levels. Please address issue.

**Comment by DaveHyral** [comment]
Bug has been fixed after I worked with the config. your _**own**_ .json/ .json5 formatting is absolutely bugged.

please use this site to further debug your own .json files, it is specifically meant for minecraft.

your code commenting was causing all kinds of non-functionality with said config files.

https://codebeautify.org/jsonviewer/2afc93

**Comment by alkyaly** [comment]
> Bug has been fixed after I worked with the config. your _**own**_ .json/ .json5 formatting is absolutely bugged.
> 
> please use this site to further debug your own .json files, it is specifically meant for minecraft.
> 
> your code commenting was causing all kinds of non-functionality with said config files.
> 
> https://codebeautify.org/jsonviewer/2afc93

I use OmegaConfig, it's not my format
Will test it, and report it there if applicable, thanks!
Although JSON5 should allow comments, and OC sets the parser as lenient

Didn't take it as disrespect, thanks for the appreciation :smile: 
About the suggestion: Just add a new object in the config for side effects with low min and max (You might not be able to do this in the current release because I made a mistake and made the option immutable, this is already fixed in-dev, and I will publish when I fix the replenishingItems)

Thanks for using it.
Will reopen the issue as a reminder to fix the config

**Comment by DaveHyral** [comment]
I've tested the attempts at a "well rested bonus" and confirmed that it is
not working for Buffs, only Enfeeblements. If it works in the next release,
this could give an absolutely massive chage and reason to sleep more than
just recovering fatigue.

**Comment by alkyaly** [comment]
Fixed in https://github.com/alkyaly/Somnia-Fabric/commit/42599c1187f00fc3df731754bf3b6939bed3074e
Will publish a new release soon
